### ISSUE TITLE
Elements not colored blue

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#1]
Observed behaviour:
The icon is not colored blue 
![image](https://cloud.githubusercontent.com/assets/28759801/26195135/0f119574-3bbb-11e7-9a0b-cbe85bfc9283.png)

Expected behaviour:
The icon should be colored blue
![image](https://cloud.githubusercontent.com/assets/28759801/26195231/581e58ba-3bbb-11e7-99b0-0fcd5a723221.png)

Observed behaviour:
The icon is not colored blue 
![image](https://cloud.githubusercontent.com/assets/28759801/26195250/6d572eaa-3bbb-11e7-8142-590d28181b09.png)

Expected behaviour:
The icon should be colored blue
![image](https://cloud.githubusercontent.com/assets/28759801/26195290/8c20b982-3bbb-11e7-859e-33714215c16a.png)

**Comment by bstarr322** [comment]
I can't save blue calculator image on my end. Maybe it comes to the lack of my Sketch app experience. Can you pls share calculator image on slack?

**Comment by hypostef** [comment]
@nickdotmulder can you help here?

**Comment by bstarr322** [comment]
Fixed
