### ISSUE TITLE
Mobile Version: Dates missing

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#10]
Observed behavior:
Mobile version of savings graph does not contain dates on horizontal axis
![screen](https://cloud.githubusercontent.com/assets/28759801/26209267/9d52f86a-3bec-11e7-958f-5be70e6dcda2.jpg)

Expected behavior:

![image](https://cloud.githubusercontent.com/assets/28759801/26209260/98c17a2e-3bec-11e7-982d-b1cdfc6fe438.png)

**Comment by nickdotmulder** [comment]
@hypostef Don't fix, unnecessary.

**Comment by bstarr322** [comment]
Fixed
