### ISSUE TITLE
Insert TrustPilot HTML Code

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#13]
Expected behavior:

Insert HTML code for TrustPilot integration after the review carousel.

The code reads (edit comment to view full code):

<div class="trustpilot-widget" data-locale="de-DE" data-template-id="56278e9abfbbba0bdcd568bc" data-businessunit-id="591d6b4b0000ff0005a2b0ed" data-style-height="60px" data-style-width="100%">
<a href="https://de.trustpilot.com/review/hypofriend.de" target="_blank">Trustpilot</a>
</div>

**Comment by bstarr322** [comment]
Pls give me trustpilot access or html code.

**Comment by hypostef** [comment]
<div class="trustpilot-widget" data-locale="de-DE" data-template-id="56278e9abfbbba0bdcd568bc" data-businessunit-id="591d6b4b0000ff0005a2b0ed" data-style-height="60px" data-style-width="100%">
<a href="https://de.trustpilot.com/review/hypofriend.de" target="_blank">Trustpilot</a>
</div>

**Comment by bstarr322** [comment]
Fixed
