### ISSUE TITLE
Adjust dropshadow on chat UI elements

### ISSUE THREAD

**Issue by nickdotmulder** [HypoFriend/HypoFriend#14]
Observed behaviour:
<img width="397" alt="screenshot 2017-05-20 12 09 53" src="https://cloud.githubusercontent.com/assets/2698549/26274906/62f996aa-3d55-11e7-9536-ca7f59c8ba57.png">

Expected behaviour:
<img width="389" alt="screenshot 2017-05-20 12 11 25" src="https://cloud.githubusercontent.com/assets/2698549/26274909/78cbcebc-3d55-11e7-9ee8-ace8548f07c8.png">

**Comment by bstarr322** [comment]
Would you like to get in touch with a mortgage expert? -> deutsch?

**Comment by nickdotmulder** [comment]
@hypostef please provide copy.

**Comment by bstarr322** [comment]
Fixed
