### ISSUE TITLE
Email Link not working

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#19]
Observed behavior:
Clicking on "E-Mail" doesn't do anything.

Expected behavior:
Left-clicking on "E-Mail" should both open email service provider. Right-clicking and opening a new tab should have info@hypofriend.de in URL address line.

![image](https://cloud.githubusercontent.com/assets/28759801/26301094/59f06e08-3ee0-11e7-89a6-691cef28da87.png)

**Comment by bstarr322** [comment]
I can see left-clicking opens email app and right-clicking opens a new tab with that email address. Pls check it exactly. @nickdotmulder, it's the same on your end?
