### ISSUE TITLE
<h2> headings not assigned

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#21]
Observed behavior:
![image](https://cloud.githubusercontent.com/assets/28759801/26302002/2183911e-3ee3-11e7-971e-e9fd409b5d85.png)

Expected behavior:
Please convert the following content into h2 headings:

English:

- Calculate mortgage savings
- Find best mortgages
- Refinance your mortgage with expert
- Refinancing options from all major German banks
- Calculate how much you could save and refinance your mortgage within two weeks

German:

- Hypotheken Ersparnisse berechnen
- Finde die besten Angebote
- Refinanziere deine Hypothek mit unseren Experten
- Refinanzierungsangebote von allen großen deutschen Banken
- Berechne, wie viel du sparen könntest und refinanziere deine Hypothek vollständig in weniger als zwei Wochen

**Comment by bstarr322** [comment]
changed main domain as .com and redirect it to .de. so observing SEO factors

**Comment by bstarr322** [comment]
added

**Comment by bstarr322** [comment]
fixed, pls use https://chrome.google.com/webstore/detail/seo-website-analysis/hlngmmdolgbdnnimbmblfhhndibdipaf/related?hl=en
