### ISSUE TITLE
Implement HTML compression

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#22]
Observed behavior:
![image](https://cloud.githubusercontent.com/assets/28759801/26304846/28e0df70-3eed-11e7-8309-8d9a1cfeb29c.png)

Expected behavior:
![image](https://cloud.githubusercontent.com/assets/28759801/26304886/4c38e06c-3eed-11e7-8029-98d5b0622f4e.png)

**Comment by bstarr322** [comment]
added. I'll check it after domain is up and running.

**Comment by bstarr322** [comment]
Fixed
