### ISSUE TITLE
Fix URL Canonicalization Test

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#23]
Oberved behavior:
![image](https://cloud.githubusercontent.com/assets/28759801/26305034/f8f76012-3eed-11e7-8c72-7c48bee820f7.png)

Expected behavior:
![image](https://cloud.githubusercontent.com/assets/28759801/26305067/14d1a6b2-3eee-11e7-939b-5ae2766d3810.png)

NOTE: same applies also for http://hypofriend.com and http://www.hypofriend.com/

**Comment by bstarr322** [comment]
added. I'll check it after domain is up and running.

**Comment by bstarr322** [comment]
Fixed
