### ISSUE TITLE
Fix HTTPS Test & Set Up SSL Protocol

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#24]
Observed behavior:
![image](https://cloud.githubusercontent.com/assets/28759801/26305183/910c9f8e-3eee-11e7-8e7b-97a722fd984b.png)

Expected behavior:
Website uses secure communication protocol, such as SSL. 

NOTE: I will take care of setting up the SSL protocol for HTTPS compliance
https://www.digitalocean.com/community/tutorials/how-to-install-an-ssl-certificate-from-a-commercial-certificate-authority

**Comment by bstarr322** [comment]
Pls send me ssl certificate, then I'll setup it on EC2.

**Comment by nickdotmulder** [comment]
@hypostef waiting for you here.

**Comment by bstarr322** [comment]
Fixed
