### ISSUE TITLE
Switch Off Serve Signature

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#25]
Observed behavior:
![image](https://cloud.githubusercontent.com/assets/28759801/26305267/e13aa79e-3eee-11e7-86a7-4a289c4854cf.png)

Expected behavior:
Serve signature should be switched off.

**Comment by bstarr322** [comment]
added. I'll check it after domain is up and running.

**Comment by bstarr322** [comment]
fixed
