### ISSUE TITLE
Implement Caching Protocol

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#26]
Observed behavior:
![image](https://cloud.githubusercontent.com/assets/28759801/26305459/a33f7856-3eef-11e7-91eb-90f5a9b05705.png)

Expected behavior:
![image](https://cloud.githubusercontent.com/assets/28759801/26305495/d0d10758-3eef-11e7-81b4-c66cafc95e29.png)

**Comment by bstarr322** [comment]
We are not using PHP even though it is deployed on EC2 Apache instance. But we are using gzip. So we don't need to use them.
