### ISSUE TITLE
Some CCS Files are not minified

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#28]
Observed behavior:
![image](https://cloud.githubusercontent.com/assets/28759801/26306298/1d143fce-3ef3-11e7-97d4-5d130d44ef51.png)

Expected behavior:

Minified CSS Files:
- http://hypofriend.de/static/css/main.4e79bd83.css- https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css- https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css- https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css

Not Minified CSS Files:
- https://fonts.googleapis.com/css?family=Fira+Sans:400,500,700,800,900- https://fonts.googleapis.com/css?family=Ubuntu:400,500,700

**Comment by bstarr322** [comment]
Fixed
