### ISSUE TITLE
Add Expired Headers to Images

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#29]
Observed behavior:
![image](https://cloud.githubusercontent.com/assets/28759801/26305610/4a6c135a-3ef0-11e7-8091-4514ffd52384.png)

Expected behavior:
Add expired headers to the following images:

- http://hypofriend.de/static/media/banner1.465b45fe.png
- http://hypofriend.de/static/media/banner2.fc4cee89.jpeg
- http://hypofriend.de/static/media/banner3.d5c54ece.jpeg
- http://hypofriend.de/static/media/de.73846544.svg
- http://hypofriend.de/static/media/gb.cdc58ce5.svg
- http://hypofriend.de/static/media/ssl.45fc1c33.svg
- http://hypofriend.de/static/media/calc.a3690c08.png
- http://hypofriend.de/static/media/find_mortgage.f7921e25.png
- http://hypofriend.de/static/media/refinance_mortgage.f72b4a60.png
- http://hypofriend.de/static/media/ekomi_logo.dcd0aa25.png
- http://hypofriend.de/favicon.ico

**Comment by bstarr322** [comment]
Fixed. But you can see that it is not fixed because "http://widget.trustpilot.com/trustboxes/56278e9abfbbba0bdcd568bc/logo-28x29.png".
So logo png must be fixed by TrustPilot
