### ISSUE TITLE
IP Canonicalization Test Failed

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#30]
Observed behavior:
![image](https://cloud.githubusercontent.com/assets/28759801/26307228/daf59394-3ef3-11e7-96f3-ebd65ec32825.png)

Expected behavior:
Redirect IP address to hypofriend.de and hypofriend.com, respectively.

**Comment by bstarr322** [comment]
added. I'll check it after domain is up and running.

**Comment by bstarr322** [comment]
Fixed
