### ISSUE TITLE
Fix Libwww-perl Access Test

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#31]
Observed behavior:
![image](https://cloud.githubusercontent.com/assets/28759801/26307320/3cb7eb4a-3ef4-11e7-8d67-a101154df641.png)

Expected behavior:
In order to pass this test you must block the libwww-perl user-agent in your .htaccess file.
If your site is running on apache server, you could put these lines in your .htaccess after RewriteEngine on line:

RewriteCond %{HTTP_USER_AGENT} libwww-perl.* 
RewriteRule .* ? [F,L]

**Comment by bstarr322** [comment]
added. I'll check it after domain is up and running.

**Comment by bstarr322** [comment]
Fixed
