### ISSUE TITLE
Create & insert sitemap.xml files

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#34]
Observed behavior:
![image](https://cloud.githubusercontent.com/assets/28759801/26312435/d1088a30-3f07-11e7-87d1-244e0e345a66.png)

Expected behavior:
Generate and place the sitemap files in the root directory of hypofriend.de and hypofriend.com

**Comment by bstarr322** [comment]
added. I'll check it after domain is up and running.

**Comment by bstarr322** [comment]
Fixed

**Comment by bstarr322** [comment]
Fixed
