### ISSUE TITLE
Desktop Hypofriend.de: Eliminate render-blocking JavaScript and CSS in above-the-fold content

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#36]
Observed behavior:
Your page has 1 blocking script resources and 1 blocking CSS resources. This causes a delay in rendering your page.

Expected behavior:

Remove render-blocking JavaScript:
http://hypofriend.de/static/js/main.617db1fc.js

Optimize CSS Delivery of the following:
http://hypofriend.de/static/css/main.4e79bd83.css

**Comment by nickdotmulder** [comment]
From Pagespeed insights: 
![Uploading Screenshot 2017-05-26 10.38.58.png…]()

**Comment by bstarr322** [comment]
Fixed
