### ISSUE TITLE
Desktop Hypofriend.de: Set Expiry Date in HTTP headers to reduce loading times

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#37]
Observed behavior:
Expiry date or a maximum age in HTTP headers for static resources not set. 
Expected behavior:

Leverage browser caching for the following cacheable resources:
https://cdn.optimizely.com/js/8387303062.js (2.1 minutes)

**Comment by bstarr322** [comment]
It's based on optimizely cdn options, so we can't change this.
