### ISSUE TITLE
Meta description in Google search results not updated for Hypofriend.de and Hypofriend.com

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#38]
Observed behavior:
Meta description still missing for hypofriend.com

![image](https://cloud.githubusercontent.com/assets/28759801/26461248/d5a1f3d4-417c-11e7-8de7-c7f4e40780d7.png)

Expected behavior:
Meta description should be added to html file

English:
"Use HypoFriend to refinance your mortgage to a lower interest rate and save €23,000 on average.

Observed behavior:
Meta description for hypofriend.de in place but not updated with regards to content
![image](https://cloud.githubusercontent.com/assets/28759801/26461417/575b43c6-417d-11e7-9340-c1a6f90f0efa.png)

Expected behavior:

Meta description (German):
"Nutze HypoFriend, um deine Hypothek auf einen niedrigeren Zinssatz zu refinanzieren. Das spart durchschnittlich €23.000 Zinsen."

**Comment by bstarr322** [comment]
Changed meta descriptions for each language. Pls check them once Google updates them

**Comment by nickdotmulder** [comment]
@bstarr322 still not updated, also im quite sure this is bad practice, i.e. having two sites index by google: 

<img width="695" alt="screenshot 2017-05-28 11 26 39" src="https://cloud.githubusercontent.com/assets/2698549/26527666/b0fb2140-4398-11e7-9898-094bcbaca94c.png">

**Comment by bstarr322** [comment]
Pls check again

**Comment by nickdotmulder** [comment]
Fixed, thx @bstarr322
