### ISSUE TITLE
Hypofriend.de: Change Meta Title

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#39]
Observed:
![image](https://cloud.githubusercontent.com/assets/28759801/26461472/84f0e0de-417d-11e7-83cb-04d6ce5c1cd5.png)

Expected:
Meta title tag should be as follows:
"Refinanziere kostenlos deine Hypothek | HypoFriend"

**Comment by bstarr322** [comment]
Changed meta title. Pls check it once Google updates it.

**Comment by bstarr322** [comment]
Fixed
