### ISSUE TITLE
Edit Customer Reviews

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#4]
Observed behavior:
Image of four customers who have used HypoFriend needs to be different for all four bubbles
![image](https://cloud.githubusercontent.com/assets/28759801/26195786/3afdea8c-3bbd-11e7-8739-45f448fcdd83.png)

Expected behavior:

1. Replace existing face of Thomas with this new image:

- Keep the text as it is

- Thomas, 37, Berlin

![thomas](https://cloud.githubusercontent.com/assets/28759801/26205970/bc5475c6-3be3-11e7-966c-e3923cbce8f2.jpg)

2. Add new image of Saskia:

- "Ich habe immer gedacht, dass es zu viel Umstand wäre meinen alten Immobilienkredit zu einer neuen Bank umzuschulden. Mein Darlehensberater von HypoFriend hat aber einen günstigeren Kreditgeber herausgesucht und die ganze bürokratische Arbeit gemacht.

- Saskia, 35, Hamburg

![saskia](https://cloud.githubusercontent.com/assets/28759801/26204382/d765d544-3bde-11e7-8581-bdeca3221a16.jpg)

3. Add new image of Alex:

- "Ich habe jahrelang eine zu hohen Zinssatz auf mein Darlehen gezahlt. Mit der Expertenhilfe von HypoFriend konnte ich kostenlos und mit wenig Aufwand Tausende Euros sparen. 

- Alex, 40, Mainz

![alex](https://cloud.githubusercontent.com/assets/28759801/26204434/028b2e22-3bdf-11e7-8ddc-95198a9af9fb.jpg)

4. Add new image of Gabriele: 

- "Durch die Refinanzierung meiner Hypothek zahle ich in meinem neuen Vertrag jetzt weniger Zinsen und kann entsprechend höher tilgen. Somit bin ich wesentlich schneller schuldenfrei.

- Gabriele, 44, Stuttgart

![gabriele](https://cloud.githubusercontent.com/assets/28759801/26204452/15f45970-3bdf-11e7-9cbb-c5345c260136.jpeg)

Each customer's face is different and comes with a different description

**Comment by bstarr322** [comment]
Pls provide me other 3 images and descriptions.

**Comment by bstarr322** [comment]
Fixed
