### ISSUE TITLE
Hypofriend.com: Set Meta title tag

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#40]
Observed:
![image](https://cloud.githubusercontent.com/assets/28759801/26461796/9ebf34ce-417e-11e7-90fd-149def6afe9d.png)

Expected:
Meta title tag should be as follows:
"Germany's First Online Mortgage Advisor | HypoFriend"

**Comment by bstarr322** [comment]
Changed meta title. Pls check it once Google updates it.

**Comment by nickdotmulder** [comment]
@bstarr322 Still not updated.

**Comment by nickdotmulder** [comment]
![image](https://cloud.githubusercontent.com/assets/2698549/26528034/84e4d796-43a1-11e7-968b-a740cb67229a.png)


based on this - lets wait again..
