### ISSUE TITLE
Desktop Hypofriend.de: Prioritize visible content

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#41]
Observed:

The entire HTML response was not sufficient to render the above-the-fold content. This usually indicates that additional resources, loaded after HTML parsing, were required to render above-the-fold content. Prioritize visible content that is needed for rendering above-the-fold by including it directly in the HTML response.
None of the final above-the-fold content could be rendered even with the full HTML response.

Expected: 
Reduce the amount of HTML needed to render above-the-fold content.

**Comment by bstarr322** [comment]
The html, css and js are optimized by webpack and at the moment the site speed is more than 90 %, so I think this is fixed.
