### ISSUE TITLE
Restyle Landing page Footer

### ISSUE THREAD

**Issue by nickdotmulder** [HypoFriend/HypoFriend#43]
Observed: 

<img width="1280" alt="screenshot 2017-05-28 11 21 41" src="https://cloud.githubusercontent.com/assets/2698549/26527623/dad9bd2e-4397-11e7-81b0-7ce6df0d7072.png">

Expected: 

See new footer: 
![landingspage](https://cloud.githubusercontent.com/assets/2698549/26527644/0b3aeff6-4398-11e7-8c86-2c580707e18d.jpg)

**Comment by nickdotmulder** [comment]
Incl. Hover effect ^

**Comment by nickdotmulder** [comment]
Be prepared to add third column with SEO relevant content next to about us. i.e. 4 column layout. 

"How to refinance" 
"Forward Mortgages"
...

**Comment by bstarr322** [comment]
I can't understand footer structure well. Pls explain in details.

**Comment by nickdotmulder** [comment]
Please use Zeplin and create the design: 

<img width="609" alt="screenshot 2017-05-29 10 32 37" src="https://cloud.githubusercontent.com/assets/2698549/26542445/27b96c6c-445a-11e7-928a-44ea3e6467a7.png">

**Comment by bstarr322** [comment]
Fixed
