### ISSUE TITLE
Add new designed favicon

### ISSUE THREAD

**Issue by nickdotmulder** [HypoFriend/HypoFriend#47]
"Bubble" 
![00_default-bubble](https://cloud.githubusercontent.com/assets/2698549/26626621/244f0c4a-45f8-11e7-8fd5-69e846a048c5.jpg)

[_Social.zip](https://github.com/HypoFriend/HypoFriend/files/1040972/_Social.zip)

**Comment by nickdotmulder** [comment]
The complete favicon zip:

[Favicon.zip](https://github.com/HypoFriend/HypoFriend/files/1045983/Favicon.zip)

**Comment by bstarr322** [comment]
Added
