### ISSUE TITLE
Add amplitude events to webapp

### ISSUE THREAD

**Issue by nickdotmulder** [HypoFriend/HypoFriend#48]
![image](https://cloud.githubusercontent.com/assets/2698549/26637846/dec6101e-4620-11e7-97ab-3de92b096efd.png)

**Screen 1**
Viewed_welcome_screen
Amplitude.event('Click.next.button', {"location": "welcome", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "welcome", "flow":"refinance" })

![image](https://cloud.githubusercontent.com/assets/2698549/26637853/e92a33aa-4620-11e7-9bd8-b4af10059416.png)

**Screen 2**
Viewed_firstname_screen
Amplitude.event('Click.next.button', {"location": "firstname", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "firstname", "flow":"refinance" })
Amplitude.event('Click.back', {"location": "firstname", "flow":"refinance" })

![image](https://cloud.githubusercontent.com/assets/2698549/26638074/85e5c916-4621-11e7-8eff-3339608d14b0.png)

**Screen 3**
Viewed_lastname_screen
Amplitude.event('Click.next.button', {"location": "lastname", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "lastname", "flow":"refinance" })
Amplitude.event('Click.back', {"location": "lastname", "flow":"refinance" })

![image](https://cloud.githubusercontent.com/assets/2698549/26638086/8cf9696a-4621-11e7-80a4-c1ebf4c3827e.png)

**Screen 4**
Viewed_zipcode_screen
Amplitude.event('Click.next.button', {"location": "zipcode", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "zipcode", "flow":"refinance" })
Amplitude.event('Click.back', {"location": "zipcode", "flow":"refinance" })
Amplitude.event('Click.info', {"location": "zipcode", "flow":"refinance" })

![image](https://cloud.githubusercontent.com/assets/2698549/26638105/9526568e-4621-11e7-9d8b-b91b3c759708.png)

**Screen 5**
Viewed_startyear_screen
Amplitude.event('Click.next.button', {"location": "startyear", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "startyear", "flow":"refinance" })
Amplitude.event('Click.back', {"location": "startyear", "flow":"refinance" })
Amplitude.event('Click.info', {"location": "startyear", "flow":"refinance" })

![image](https://cloud.githubusercontent.com/assets/2698549/26638245/f8dd2f5e-4621-11e7-90c4-05e2d0f3dbe9.png)

**Screen 6**
Viewed_askrefinance_screen
Amplitude.event('Click.next.button', {"location": "askrefinance", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "askrefinance", "flow":"refinance" })
Amplitude.event('Click.back', {"location": "askrefinance", "flow":"refinance" })
Amplitude.event('Click.info', {"location": "askrefinance", "flow":"refinance" })

**Screen 7**
Viewed_refinanced_screen
Amplitude.event('Click.next.button', {"location": "refinanced", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "refinanced", "flow":"refinance" })
Amplitude.event('Click.back', {"location": "refinanced", "flow":"refinance" })
Amplitude.event('Click.info', {"location": "refinanced", "flow":"refinance" })

**Screen 8**
Viewed_interestperiod_screen
Amplitude.event('Click.next.button', {"location": "interestperiod", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "interestperiod", "flow":"refinance" })
Amplitude.event('Click.back', {"location": "interestperiod", "flow":"refinance" })
Amplitude.event('Click.info', {"location": "interestperiod", "flow":"refinance" })

**Screen 8**
Viewed_loanbalance_screen
Amplitude.event('Click.next.button', {"location": "loanbalance", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "loanbalance", "flow":"refinance" })
Amplitude.event('Click.back', {"location": "loanbalance", "flow":"refinance" })
Amplitude.event('Click.info', {"location": "loanbalance", "flow":"refinance" })

**Screen 9**
Viewed_interestrate_screen
Amplitude.event('Click.next.button', {"location": "interestrate", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "interestrate", "flow":"refinance" })
Amplitude.event('Click.back', {"location": "interestrate", "flow":"refinance" })
Amplitude.event('Click.info', {"location": "interestrate", "flow":"refinance" })

**Screen 10**
Viewed_monthlypayment_screen
Amplitude.event('Click.next.button', {"location": "monthlypayment", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "monthlypayment", "flow":"refinance" })
Amplitude.event('Click.back', {"location": "monthlypayment", "flow":"refinance" })
Amplitude.event('Click.info', {"location": "monthlypayment", "flow":"refinance" })

**Screen 11**
Viewed_remainingyears_screen
Amplitude.event('Click.next.button', {"location": "remainingyears", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "remainingyears", "flow":"refinance" })
Amplitude.event('Click.back', {"location": "remainingyears", "flow":"refinance" })
Amplitude.event('Click.info', {"location": "remainingyears", "flow":"refinance" })

**Screen 12**
Viewed_remortgageyear_screen
Amplitude.event('Click.next.button', {"location": "remortgageyear", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "remortgageyear", "flow":"refinance" })
Amplitude.event('Click.back', {"location": "remortgageyear", "flow":"refinance" })
Amplitude.event('Click.info', {"location": "remortgageyear", "flow":"refinance" })

**Screen 13**
Viewed_email_screen
Amplitude.event('Click.finish', {"location": "email", "flow":"refinance" })
Properties for Finish event: 
start_year i.e. (1990)
zipcode i.e. (10245)
refinanced i.e. (yes/no)
refinance_year i.e. (2016)
remaining_years i.e. (3)
monthly_payment i.e. (4000)
remortgage_year i.e. (1998)
interest_period i.e. (10 years)
loan_balance i.e. (10000)
interest_rate i.e. (4.5%)
email i.e. (xxx@email.com)

Amplitude.event('Click.menu', {"location": "email", "flow":"refinance" })
Amplitude.event('Click.back', {"location": "email", "flow":"refinance" })
Amplitude.event('Click.info', {"location": "email", "flow":"refinance" })

**Screen 14**
Viewed_loading_screen

**Screen 15**
Viewed_result_screen
Amplitude.event('Click.continue.button', {"location": "**top/bottom**", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "result", "flow":"refinance" })

**Screen 16**
Viewed_phonenumber_screen
Amplitude.event('Click.back', {"location": "phonenumber", "flow":"refinance" })
Amplitude.event('Click.next.button', {"location": "phonenumber", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "phonenumber", "flow":"refinance" })

**Screen 17**
Viewed_availability_screen
Amplitude.event('Click.next.button', {"location": "availability", "flow":"refinance" })
Amplitude.event('Click.back', {"location": "availability", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "availability", "flow":"refinance" })

**Screen 18**
Viewed_feedback_screen
Amplitude.event('Click.next.button', {"location": "feedback", "flow":"refinance" })
Amplitude.event('Click.back', {"location": "feedback", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "feedback", "flow":"refinance" })

**Screen 19**
Viewed_thankyou_screen
Amplitude.event('Click.next.button', {"location": "thankyou", "flow":"refinance" })
Amplitude.event('Click.back', {"location": "thankyou", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "thankyou", "flow":"refinance" })

**Comment by nickdotmulder** [comment]
@bstarr322 checking the events; we're missing the click.finish event on Screen 13 with the properties; 

Screen 13
Viewed_email_screen
Amplitude.event('Click.finish', {"location": "email", "flow":"refinance" })
Properties for Finish event:
start_year i.e. (1990)
zipcode i.e. (10245)
refinanced i.e. (yes/no)
refinance_year i.e. (2016)
remaining_years i.e. (3)
monthly_payment i.e. (4000)
remortgage_year i.e. (1998)
interest_period i.e. (10 years)
loan_balance i.e. (10000)
interest_rate i.e. (4.5%)
email i.e. (xxx@email.com)

**Comment by nickdotmulder** [comment]
Also missing events for:

Screen 17
Viewed_availability_screen
Amplitude.event('Click.next.button', {"location": "availability", "flow":"refinance" })
Amplitude.event('Click.back', {"location": "availability", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "availability", "flow":"refinance" })

**Comment by nickdotmulder** [comment]
@bstarr322 we are missing the page: 'startyear' i.e. screen 5

Screen 5
Viewed_startyear_screen
Amplitude.event('Click.next.button', {"location": "startyear", "flow":"refinance" })
Amplitude.event('Click.menu', {"location": "startyear", "flow":"refinance" })
Amplitude.event('Click.back', {"location": "startyear", "flow":"refinance" })
Amplitude.event('Click.info', {"location": "startyear", "flow":"refinance" })

**Comment by bstarr322** [comment]
![image](https://user-images.githubusercontent.com/15979250/27420557-0f6bf3cc-572f-11e7-82fe-d8dd28322d36.png)
![image](https://user-images.githubusercontent.com/15979250/27420560-14fd991c-572f-11e7-9d2b-25579a4a12e1.png)

Screen 5 events exist

In screen 13, the following properties should be included in the event?
start_year i.e. (1990)
zipcode i.e. (10245)
refinanced i.e. (yes/no)
refinance_year i.e. (2016)
remaining_years i.e. (3)
monthly_payment i.e. (4000)
remortgage_year i.e. (1998)
interest_period i.e. (10 years)
loan_balance i.e. (10000)
interest_rate i.e. (4.5%)
email i.e. (xxx@email.com)

**Comment by nickdotmulder** [comment]
@bstarr322 there is no screen called "startyear" and yes please add the properties to screen 13 in the finish event.



<img width="1280" alt="screen shot 2017-06-22 at 6 02 54 pm" src="https://user-images.githubusercontent.com/2698549/27443965-0cd07232-5775-11e7-9831-8857532a4220.png">
<img width="1280" alt="screen shot 2017-06-22 at 6 02 59 pm" src="https://user-images.githubusercontent.com/2698549/27443966-0cd50a4a-5775-11e7-8ece-639e6c74c437.png">

**Comment by bstarr322** [comment]
Fixed
