### ISSUE TITLE
Hyperlink to Trustpilot.com/hypofriend missing

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#5]
Observed behavior:
Clicking on TrustPilot icon does not open TrustPilot page for HypoFriend
![image](https://cloud.githubusercontent.com/assets/28759801/26196083/15a6375c-3bbe-11e7-8ac9-cef5f189e2de.png)

Expected behavior:
Clicking on TrustPilot icon should open TrustPilot page for HypoFriend

**Comment by bstarr322** [comment]
Fixed
