### ISSUE TITLE
Add logo to top bar next to "HypoFriend"

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#50]
Observed:
![image](https://user-images.githubusercontent.com/28759801/26881753-a7d5d9b8-4b98-11e7-9efc-1b6f665e616a.png)

HypoFriend lacks the new logo

Expected:
![image](https://user-images.githubusercontent.com/28759801/26881823-e36d6a22-4b98-11e7-95d1-962e7b861e6b.png)

**Comment by bstarr322** [comment]
done

**Comment by nickdotmulder** [comment]
Please use SVG.

**Comment by nickdotmulder** [comment]
You're not using SVG @bstarr322

**Comment by nickdotmulder** [comment]
See Slack for file.

**Comment by bstarr322** [comment]
Fixed
