### ISSUE TITLE
Clicking on "Email Letter" icon does not do anything

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#51]
Observed:
![image](https://user-images.githubusercontent.com/28759801/26882048-8c4c359c-4b99-11e7-9d51-faa746ca4e10.png)

Expected:
- Left-clicking on the email letter icon should open user's default email service provider with info@hypofriend.de as a recipient.
- Right-clicking on the email letter icon and opening a new tab should have info@hypofriend.de in the URL

**Comment by bstarr322** [comment]
It has already been working correctly. Strange that it does not work on your end.

**Comment by nickdotmulder** [comment]
Seems to work.
