### ISSUE TITLE
Step #3: Translation missing

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#56]
Observed:
![image](https://user-images.githubusercontent.com/28759801/27385051-8146e18a-5691-11e7-8abe-c12e434c4f4b.png)

Expected:
English and German are still mixed up.

"Or click enter" should be replaced with "Or press enter" where applicable.

German translation should be "Oder Enter drücken"

**Comment by bstarr322** [comment]
Fixed
