### ISSUE TITLE
Step #3: change text

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#57]
Observed:
![image](https://user-images.githubusercontent.com/28759801/27385507-398120de-5693-11e7-8ce3-809c79efd99f.png)

Expected:
Change English and German texts so the step looks as follows:

- Thomas, can you also tell me your last name?
- Thomas, sagst du mir auch, wie dein Nachname lautet?

**Comment by bstarr322** [comment]
Fixed
