### ISSUE TITLE
Step #4: translation in "zip code" bubble missing

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#58]
Observed:
![image](https://user-images.githubusercontent.com/28759801/27385615-935191b6-5693-11e7-8fec-209b5d256adc.png)

Expected:
Hovering over the information bubble should display the following text:

(i) Zip code
The zip code determines the location of the property that you currently have a mortgage for. Banks differentiate the interest rate somewhat based on the location of your property.

(i) PLZ
Die PLZ bestimmt den Standort der Immobilie, die du mit deinem Darlehen finanzierst. Abhängig vom Immobilienstandort, bieten regionale Banken zum Teil verschiedene Zinsraten für Darlehen an.

**Comment by bstarr322** [comment]
Fixed
