### ISSUE TITLE
Step #7: edit text

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#61]
Observed:
![image](https://user-images.githubusercontent.com/28759801/27390473-9c632a18-56a1-11e7-9282-e89c89fb069a.png)

Expected:
Edit text so that it reads:

- Let’s talk about your mortgage. Have you refinanced your mortgage since living there?
- Lass uns über dein Darlehen sprechen. Hast du dein Darlehen seit deinem Einzug schon einmal umgeschuldet?

**Comment by bstarr322** [comment]
Fixed
