### ISSUE TITLE
Step #7 + #8: translation for info bubble missing

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#62]
Observed:
![image](https://user-images.githubusercontent.com/28759801/27390584-f3144694-56a1-11e7-97a9-997affe6f09f.png)

Expected:
English and German text in the bubble should be:

(i) Refinancing
Refinancing a mortgage means that you are getting a new mortgage to replace the old one. If you have refinanced your mortgage before, we need to know your refinancing date to determine when is the best moment to refinance again.

(i) Umschuldung
Bei einer Umschuldung wird das alte Darlehen durch ein neues Darlehen abgelöst. Wenn du dein Darlehen bereits schon einmal umgeschuldet hast, brauchen wir das Datum dieser Umschuldung. Dadurch können wir bestimmen, wann der bestmögliche Zeitpunkt ist, dein Darlehen erneut umzuschulden.

**Comment by bstarr322** [comment]
Fixed
