### ISSUE TITLE
Social media integrations missing in the footer

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#7]
Observed behavior:
Social media integrations missing

Expected behavior:
Social media integrations to be displayed in the footer
Example: ![image](https://cloud.githubusercontent.com/assets/28759801/26197820/f3ce4088-3bc3-11e7-8f31-c69c2178631f.png)

Contact → Kontakt info@hypofriend.de 
Facebook → www.facebook.com/hypofriend 
Instagram → https://www.instagram.com/hypofriend/ 
Youtube → https://www.youtube.com/channel/UC1v8bbt8BxWdHAcErx-YKFA
Twitter → https://twitter.com/HypoFriendDE

**Comment by nickdotmulder** [comment]
@hypostef This ticket doesn't make sense - where is this view supposed to fit?

**Comment by hypostef** [comment]
@nickdotmulder 

I was thinking of using the template that clark.de uses here:
![image](https://cloud.githubusercontent.com/assets/28759801/26206046/fb242c10-3be3-11e7-9ca7-5ffef9a0ee84.png)

I would structure the footer as follows:

**LEFT COLUMN:**

- Über uns
- Blog
- Häufige Fragen


**RIGHT COLUMN:**

Kontaktiere uns

E-Mail: info@hypofriend.de
Facebook → www.facebook.com/hypofriend
Instagram → https://www.instagram.com/hypofriend/
Youtube →
Twitter → https://twitter.com/HypoFriendDE


INCLUDE THESE IMAGES BELOW THE TWO COLUMNS:

![image](https://cloud.githubusercontent.com/assets/28759801/26206439/217196c2-3be5-11e7-9238-8761afebd752.png)

![image](https://cloud.githubusercontent.com/assets/28759801/26206483/424ae3b2-3be5-11e7-9ac0-7789ccc8cec3.png)

![image](https://cloud.githubusercontent.com/assets/28759801/26206504/4c129f20-3be5-11e7-9360-bdff657693db.png)



BOTTOM ROW BELOW THE THREE IMAGES THAT CONTAINS:

Impressum
AGB
Datenschutz

**Comment by bstarr322** [comment]
Added

**Comment by hypostef** [comment]
Observed behavior:
Clicking on "E-Mail" doesn't do anything.


Expected behavior:
Left-clicking on "E-Mail" should both open email service provider. Right-clicking and opening a new tab should have info@hypofriend.de in URL address line.

![image](https://cloud.githubusercontent.com/assets/28759801/26301094/59f06e08-3ee0-11e7-89a6-691cef28da87.png)
