### ISSUE TITLE
Step #14: info bubble for "Vorfälligkeitsentschädigung" missing

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#70]
Observed:
![image](https://user-images.githubusercontent.com/28759801/27392993-63ef88b4-56a8-11e7-930f-152cda08fe74.png)

Expected:
The pre-payment penalty ("Vorfälligkeitsentschädigung" in German) should have an info bubble icon that contains the following content:

(i) Pre-payment penalty 
By refinancing and paying back your old mortgage earlier than agreed upon, your bank misses out on the interest payments they would have otherwise received from you. To compensate for these interest losses, banks charge mortgage owners substantial bank penalty fees. If you have had your mortgage for more than 10 years, German law §489 allows you to leave a mortgage agreement and refinance to a new loan without paying any penalty fees.

(i) Vorfälligkeitsentschädigung
Mit einer Umschuldung und einer vorzeitigen Rückzahlung deines Darlehens, entgehen einer Bank geplante Zinseinnahmen, die sie sonst eingenommen hätte. Um diese Einnahmen auszugleichen, verlangen Banken eine erhebliche Vorfälligkeitsentschädigung. Wenn du dein Darlehen aber schon länger als 10 Jahre abbezahlt hast, kannst du laut §489 im Bürgerlichen Gesetzbuch OHNE Vorfälligkeitsentschädigung dein Darlehen zu einer anderen Bank umschulden.

**Comment by bstarr322** [comment]
Fixed
