### ISSUE TITLE
Height of webapp not correct, cannot click next

### ISSUE THREAD

**Issue by nickdotmulder** [HypoFriend/HypoFriend#71]
I cannot click the next button on this screen because it is hidden under another element, its hard to proceed to the next screen. 

<img width="1280" alt="screen shot 2017-06-23 at 11 57 00 am" src="https://user-images.githubusercontent.com/2698549/27477054-50bf04e0-580b-11e7-8fd1-99ae172b0b79.png">

**Comment by bstarr322** [comment]
Fixed
