### ISSUE TITLE
Pressing enter on StartYear screen doesnt go to next.

### ISSUE THREAD

**Issue by nickdotmulder** [HypoFriend/HypoFriend#72]
Pressing enter on StartYear screen doesnt go to next after i have selected the date and year.

<img width="1280" alt="screen shot 2017-06-23 at 11 59 32 am" src="https://user-images.githubusercontent.com/2698549/27477117-81105cd4-580b-11e7-9acd-3222b82c9c56.png">

**Comment by bstarr322** [comment]
Fixed
