### ISSUE TITLE
Desktop: Language switching functionality in web app not available

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#75]
Observed:
![image](https://user-images.githubusercontent.com/28759801/27478710-1acd4c74-5811-11e7-90d0-cbf706fdd2a2.png)

Expected:
Add drop down functionality in top right corner so that users can switch between German and English.

![image](https://user-images.githubusercontent.com/28759801/27478725-29f728e6-5811-11e7-9dcd-acadb0aaf3e6.png)

**Comment by bstarr322** [comment]
Fixed
