### ISSUE TITLE
Desktop + Mobile: Translation of months into German missing

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#78]
Observed:
![image](https://user-images.githubusercontent.com/28759801/27479174-13550d68-5813-11e7-83ba-73f984077e81.png)

Expected:
The acronym translations for the months in German should be:

- Jan
- Feb
- Mär
- Apr
- Mai
- Jun
- Jul
- Aug
- Sep
- Okt
- Nov
- Dez

**Comment by bstarr322** [comment]
Fixed
