### ISSUE TITLE
Desktop + Mobile: edit German content

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#79]
Observed:
![image](https://user-images.githubusercontent.com/28759801/27479477-5850e490-5814-11e7-9bae-f26e33915ecb.png)

Expected:
Replace "Refinanzierung" with "Umschuldung" so that both in desktop and mobile it reads "Hypothek - Umschuldung"

**Comment by bstarr322** [comment]
Fixed
