### ISSUE TITLE
Desktop + Mobile: edit info bubble 

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#80]
Observed:
![image](https://user-images.githubusercontent.com/28759801/27479873-01e9130a-5816-11e7-84f5-04c4b825b79c.png)

Expected:
Replace "Zinsbindung" with "Zinsbindungsdauer"
Also, update German content inside the info bubble so that it reads:

Zinsbindungsdauer
Die Zinsbindungsdauer bezieht sich auf die vertraglich vereinbarte Laufzeit deiner Hypothek. Fast die Hälfte aller deutschen Darlehensnehmer haben eine Zinsbindung von 10 Jahren. Dabei verbleibt in den meisten Fällen eine Restschuld am Ende der Zinsbindungsdauer, da Darlehen in der Regel mehr als 30 Jahre lang zurückgezahlt werden.

**Comment by bstarr322** [comment]
Fixed
