### ISSUE TITLE
Mobile: grey line of input form missing

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#81]
Observed:
![image](https://user-images.githubusercontent.com/28759801/27480044-c65b340c-5816-11e7-938a-3e0cfa9fc3e8.png)

Expected:
Grey line missing in mobile version

![image](https://user-images.githubusercontent.com/28759801/27480052-cb8aa408-5816-11e7-8ef4-7e658ce020b6.png)

**Comment by bstarr322** [comment]
I cannot find this issue. What resolution is it in?

**Comment by bstarr322** [comment]
Yeah, fixed. Pls check it again.

**Comment by nickdotmulder** [comment]
Fixed
