### ISSUE TITLE
Desktop + Mobile: update info bubble content

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#83]
Observed:
![image](https://user-images.githubusercontent.com/28759801/27480539-9b4c15e0-5818-11e7-993d-1a67ac041fc9.png)

Expected:
Please update content inside info bubble to:

Zinssatz
Das ist der Zinssatz, der vertraglich für die Dauer deiner Zinsbindung festgeschrieben wurde.

**Comment by bstarr322** [comment]
Fixed
