### ISSUE TITLE
Mobile: input field for interest rate 

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#84]
Observed:
![image](https://user-images.githubusercontent.com/28759801/27480609-dea7efb2-5818-11e7-8548-1f8f31ecd95e.png)

Expected:
In English and German versions, inserting an interest rate in X,X format does not permit advancing to next step. At the moment, only X.X format works. Both formats should work

**Comment by bstarr322** [comment]
Similar to #81
