### ISSUE TITLE
Mobile: padding overlaps with input form

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#86]
Observed:
![image](https://user-images.githubusercontent.com/28759801/27480763-b43f6d76-5819-11e7-93f1-dfec8302d645.png)

Expected:

- Separate padding from input form for email address.

- Replace existing text in this step so with the following:

To finalize calculating your savings, I’ll need to know which email address you would like to use.

Ich bin fast fertig mit der Berechnung deiner Ersparnisse. Ich muss nur noch wissen, welche E-Mail Adresse du gerne verwenden möchtest.

**Comment by bstarr322** [comment]
Fixed
