### ISSUE TITLE
Mobile: bank logos missing + padding misaligned

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#87]
Observed:
![image](https://user-images.githubusercontent.com/28759801/27480999-d76cfea2-581a-11e7-8a31-d49e17da7ff5.png)

See Zeplin.

**Comment by bstarr322** [comment]
according to mobile design, only COMMERZBANK logo in it

**Comment by nickdotmulder** [comment]
For the mobile design lets just remove the logos @bstarr322

**Comment by bstarr322** [comment]
Fixed
