### ISSUE TITLE
Change copy so that copy fits *missing translation* 

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#88]
Observed:
![image](https://user-images.githubusercontent.com/28759801/27481139-6c64bd56-581b-11e7-85cb-44e0711ef69b.png)

Expected:

<img width="251" alt="screen shot 2017-06-23 at 4 21 32 pm" src="https://user-images.githubusercontent.com/2698549/27486195-1999a496-5830-11e7-8cf1-533276454db2.png">

**Comment by nickdotmulder** [comment]
@hypostef missing translation.

**Comment by bstarr322** [comment]
I've made some changes, do you mean the current one?

**Comment by nickdotmulder** [comment]
Fixed, thanks.
