### ISSUE TITLE
Mobile + desktop: german mixed up with english

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#89]
Observed:
![image](https://user-images.githubusercontent.com/28759801/27481240-ec35c318-581b-11e7-843d-639cd0653314.png)

Expected:
The text in Eng (and German) should be as follows:

Consultation - availability
- Beratung - Verfügbarkeit

Which day can we best give you a call?
- An welchem Datum können wir dich am besten anrufen?

Next
- Weiter

**Comment by bstarr322** [comment]
Fixed
