### ISSUE TITLE
Translation missing

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#9]
Observed behavior:
Needs to be translated into German

![image](https://cloud.githubusercontent.com/assets/28759801/26203706/91d9e4d6-3bdc-11e7-97f5-446dbedce0de.png)

Expected behavior:

German translation reads: "HypoFriend hat schon 1285 Deutschen bei der Refinanzierung Ihrer Hypothek geholfen"

**Comment by bstarr322** [comment]
Fixed
