### ISSUE TITLE
Mobile + desktop: translation missing

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#92]
Observed:
![image](https://user-images.githubusercontent.com/28759801/27481743-8aaff642-581e-11e7-86c5-d30c30d91175.png)

Expected:
Replace the text as follows:

Consultation - completed
Beratung - Vollständig

Thank you, Stephan. We will be in touch soon.
Danke, Stephan. Wir kontaktieren dich in Kürze.

Back to start
Zurück zum Anfang

**Comment by nickdotmulder** [comment]
@hypostef I dont understand; 
Consultation - completion
Beratung - Vollständig

**Comment by bstarr322** [comment]
Fixed
