### ISSUE TITLE
Fix progress bar UI

### ISSUE THREAD

**Issue by nickdotmulder** [HypoFriend/HypoFriend#93]
1. its not rounded
2. there are no shadows
3. use the right colors

observed: 

<img width="1273" alt="screen shot 2017-06-24 at 9 50 16 am" src="https://user-images.githubusercontent.com/2698549/27506844-af1819a2-58c2-11e7-958c-bbe8e1f9a3b8.png">

expected: 
<img width="835" alt="screen shot 2017-06-24 at 9 50 35 am" src="https://user-images.githubusercontent.com/2698549/27506845-b21b2f5e-58c2-11e7-96b6-09a0c823f44a.png">

**Comment by bstarr322** [comment]
Fixed
