### ISSUE TITLE
Form fields should be preselected when typing

### ISSUE THREAD

**Issue by nickdotmulder** [HypoFriend/HypoFriend#94]
To increase the conversion, users should not have to click the form, the form should be pre-selected;

<img width="702" alt="screen shot 2017-06-24 at 9 52 34 am" src="https://user-images.githubusercontent.com/2698549/27506853-f2185c4e-58c2-11e7-891d-b6390010e5bd.png">

For example;

<img width="726" alt="screen shot 2017-06-24 at 9 53 49 am" src="https://user-images.githubusercontent.com/2698549/27506859-0ba87432-58c3-11e7-9e81-2971600dc98f.png">

**Comment by bstarr322** [comment]
Fixed
