### ISSUE TITLE
Fix event for homepage

### ISSUE THREAD

**Issue by nickdotmulder** [HypoFriend/HypoFriend#96]
Expected:

To see 'Visited Homepage' i.e. to use 'Homepage'

Observed:

Viewed HomePage Page

<img width="1041" alt="screen shot 2017-06-24 at 10 21 01 am" src="https://user-images.githubusercontent.com/2698549/27507020-deabcaf2-58c6-11e7-9d3b-4a57f499f2fa.png">

<img width="1038" alt="screen shot 2017-06-24 at 10 16 45 am" src="https://user-images.githubusercontent.com/2698549/27507000-6824661e-58c6-11e7-8e19-6683d2249581.png">

**Comment by bstarr322** [comment]
It is only possible: "Viewed xxx Page", so "Viewed Home Page" is possible.
